// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKwhI0E5S5Umt3YzMyTrdL5ba9xebW6aI',
    appId: '1:30163330008:web:305a85fccf1631be0248ad',
    messagingSenderId: '30163330008',
    projectId: 'yize-chatapp',
    authDomain: 'yize-chatapp.firebaseapp.com',
    storageBucket: 'yize-chatapp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPxMc8y1FLaqX5QMyj9mHJb9ZqLHhO6MI',
    appId: '1:30163330008:android:e4cf1b727ad94e0d0248ad',
    messagingSenderId: '30163330008',
    projectId: 'yize-chatapp',
    storageBucket: 'yize-chatapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnf-ZV7TDzPk6UrbbXirOMQj8HaY6TQIg',
    appId: '1:30163330008:ios:30b35124e38476a00248ad',
    messagingSenderId: '30163330008',
    projectId: 'yize-chatapp',
    storageBucket: 'yize-chatapp.appspot.com',
    iosClientId: '30163330008-tjkvm7al4p6kn6egslqnsfj1ircpala4.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnf-ZV7TDzPk6UrbbXirOMQj8HaY6TQIg',
    appId: '1:30163330008:ios:c24a0effbb4d2fad0248ad',
    messagingSenderId: '30163330008',
    projectId: 'yize-chatapp',
    storageBucket: 'yize-chatapp.appspot.com',
    iosClientId: '30163330008-8s44eepgbj4n1vk9sk8v84c9i3191fmi.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
